#!/usr/bin/env bash
# Makes sure nginx is listening on port 80 for all IPv4
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i '/status)/a \\t\tdo_stop' /etc/init.d/nginx
sudo service nginx start
