#!/usr/bin/env bash
# Takes transfers a file from one host to another using scp
if [ -z "$4" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
