#!/usr/bin/env bash
# Installs an nginx server and has the main page server some text
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
